package errors

// Policies maps error codes to their handling policies.
var Policies = map[int]Policy{

	// ─── 认证失败 (HTTP 401) ────────────────────────────────────────────────────

	10021: {
		Code:         10021,
		HTTPStatus:   401,
		Message:      "Token Not Exist",
		Category:     CategoryAuth,
		Retryable:    true,
		RefreshToken: true,
		MaxRetry:     1,
		UserHint:     "Token 不存在，正在重新获取。",
		DevHint:      "10021: plugin_token 未传或已过期，刷新 token 后重试。",
	},
	10022: {
		Code:         10022,
		HTTPStatus:   401,
		Message:      "Check Token Failed",
		Category:     CategoryAuth,
		Retryable:    true,
		RefreshToken: true,
		MaxRetry:     1,
		UserHint:     "Token 校验失败，正在重新获取。",
		DevHint:      "10022: plugin_token 签名或内容校验失败，刷新 token 后重试。",
	},
	10301: {
		Code:         10301,
		HTTPStatus:   401,
		Message:      "Check Token Perm Failed",
		Category:     CategoryAuth,
		Retryable:    true,
		RefreshToken: true,
		MaxRetry:     1,
		UserHint:     "Token 权限校验失败，正在重新获取。",
		DevHint:      "10301: token 无权限，可能需要重新刷新 token。请检查：1) 是否申请了接口权限 2) 是否发布了版本 3) 插件是否安装 4) 空间是否存在。",
	},
	10302: {
		Code:         10302,
		HTTPStatus:   401,
		Message:      "Check User Error, User Is Resigned",
		Category:     CategoryAuth,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "用户已离职，无法执行操作。",
		DevHint:      "10302: 用户已从飞书组织离职，无法继续使用。请更换为在职用户。",
	},

	// ─── 权限不足 (HTTP 403) ───────────────────────────────────────────────────

	10001: {
		Code:         10001,
		HTTPStatus:   403,
		Message:      "No Permission",
		Category:     CategoryPermission,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "没有操作权限，请检查接口权限、版本发布、插件安装状态和空间权限。",
		DevHint:      "10001: 无权限。请检查：1) 当前用户是否具有空间访问权限 2) 插件是否已在对应空间安装 3) 插件版本是否已发布。",
	},
	10002: {
		Code:         10002,
		HTTPStatus:   403,
		Message:      "Illegal Operation",
		Category:     CategoryPermission,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "非法操作，当前节点或状态不允许流转到指定目标。",
		DevHint:      "10002: 操作不符合流程约束，例如尝试将节点流转到不允许的状态。请检查工作流配置。",
	},
	10004: {
		Code:         10004,
		HTTPStatus:   403,
		Message:      "Operation Failed",
		Category:     CategoryPermission,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "操作失败，该操作会导致流程图节点消失，而流程图至少需存在一个节点。",
		DevHint:      "10004: 操作会导致流程图完整性被破坏，不允许执行。请检查节点流配置。",
	},
	10210: {
		Code:         10210,
		HTTPStatus:   403,
		Message:      "code invalid",
		Category:     CategoryPermission,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "授权码无效，请重新获取。",
		DevHint:      "10210: 获取用户访问凭证时入参的授权码无效，需要重新获取。",
	},
	10211: {
		Code:         10211,
		HTTPStatus:   403,
		Message:      "Token Info Is Invalid",
		Category:     CategoryPermission,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "Token 信息不合法，请确认是否已传 X-User-Key 或插件 token 格式是否正确。",
		DevHint:      "10211: plugin_token 无法解析出具体信息，或缺少 X-User-Key header。请检查请求头是否正确传递。",
	},
	10404: {
		Code:         10404,
		HTTPStatus:   403,
		Message:      "No Project Permission",
		Category:     CategoryPermission,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "没有空间访问权限，请联系空间管理员获取授权。",
		DevHint:      "10404: 当前操作用户没有目标空间的访问权限，请确认用户已被添加到对应空间。",
	},

	// ─── 请求限流 (HTTP 429) ───────────────────────────────────────────────────

	10429: {
		Code:         10429,
		HTTPStatus:   429,
		Message:      "API Request Frequency Limit",
		Category:     CategoryRateLimit,
		Retryable:    true,
		RefreshToken: false,
		MaxRetry:     3,
		UserHint:     "请求过于频繁，正在稍后重试。",
		DevHint:      "10429: 超过同一 token 请求同一接口 15qps 限制。请实现指数退避重试，避免频繁触发限流。",
	},
	10430: {
		Code:         10430,
		HTTPStatus:   429,
		Message:      "API Request Idempotent Limit",
		Category:     CategoryRateLimit,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "请求幂等性限制，请检查是否有并发重复请求。",
		DevHint:      "10430: 同一 token 对同一接口的幂等性校验未通过，可能是短时间内重复请求。请使用唯一 idempotency_key 或间隔请求。",
	},

	// ─── 参数错误 (HTTP 400, 2xxxx) ────────────────────────────────────────────

	20001: {
		Code:        20001,
		HTTPStatus:  400,
		Message:     "Param Request Limit",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "参数超限：传入的空间 ID 超过最大 100 个的限制。",
		DevHint:     "20001: 获取空间详情时传入的空间 id 数量超过限制，请减少数量后重试。",
	},
	20002: {
		Code:        20002,
		HTTPStatus:  400,
		Message:     "Page Size Limit",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "参数超限：page_size 超过最大 200 的限制。",
		DevHint:     "20002: 查询评论时 page_size 超过限制，请减少分页大小后重试。",
	},
	20003: {
		Code:        20003,
		HTTPStatus:  400,
		Message:     "Wrong WorkItemType Param",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "参数错误：work_item_type_keys 未填写。",
		DevHint:     "20003: 获取工作项列表时缺少必需参数 work_item_type_keys。",
	},
	20004: {
		Code:        20004,
		HTTPStatus:  400,
		Message:     "Search User Limit",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "参数超限：user_keys 超过最大 10 个的限制。",
		DevHint:     "20004: 获取工作项列表时 user_keys 数量超限，请减少后重试。",
	},
	20005: {
		Code:        20005,
		HTTPStatus:  400,
		Message:     "Missing Param",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "参数缺失：必填的请求参数未填写。",
		DevHint:     "20005: 请求中缺少必填参数，请检查 API 文档中必需参数是否全部传入。",
	},
	20006: {
		Code:        20006,
		HTTPStatus:  400,
		Message:     "Invalid Param",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "参数格式错误，请检查参数类型和格式是否匹配。",
		DevHint:     "20006: 请求参数类型或格式不合法，请检查字段格式是否与 API 要求匹配。",
	},
	20007: {
		Code:        20007,
		HTTPStatus:  400,
		Message:     "WorkItem Is Already Aborted",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项已被终止，无法重复执行终止操作。",
		DevHint:     "20007: 工作项状态已是终止状态，请确认操作幂等性或使用正确的工作项 ID。",
	},
	20008: {
		Code:        20008,
		HTTPStatus:  400,
		Message:     "WorkItem Is Already Restored",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项已恢复，无法重复执行恢复操作。",
		DevHint:     "20008: 工作项状态已是正常状态，请确认操作幂等性。",
	},
	20009: {
		Code:        20009,
		HTTPStatus:  400,
		Message:     "Abort Or Restore WorkItem No Reason",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "终止或恢复工作项时缺失了原因说明。",
		DevHint:     "20009: 终止或恢复工作项需要提供原因参数，请补充后重试。",
	},
	20010: {
		Code:        20010,
		HTTPStatus:  400,
		Message:     "WorkItemType Is Not Same",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项 ID 列表中存在不同类型的工作项，无法批量操作。",
		DevHint:     "20010: 创建或更新视图时，传入的工作项 ID 列表必须是同一种工作项类型。",
	},
	20011: {
		Code:        20011,
		HTTPStatus:  400,
		Message:     "Input View Is Not Fix View",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "删除固定视图失败：指定的视图不是固定视图。",
		DevHint:     "20011: 尝试删除的视图不是固定视图，无法删除。请确认视图类型。",
	},
	20012: {
		Code:        20012,
		HTTPStatus:  400,
		Message:     "View Is Not In The Input Project",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "视图不属于指定的空间，无法在该空间下操作。",
		DevHint:     "20012: 视图所属空间与请求参数中的空间不匹配，请检查空间 ID。",
	},
	20013: {
		Code:        20013,
		HTTPStatus:  400,
		Message:     "Invalid Time Interval",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "时间参数格式错误，必须是毫秒级时间戳（13位数字）。",
		DevHint:     "20013: 时间相关参数必须是毫秒时间戳（13位），例如 1710000000000。",
	},
	20014: {
		Code:        20014,
		HTTPStatus:  400,
		Message:     "Project And WorkItem Not Match",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项所属空间与传入的空间不匹配。",
		DevHint:     "20014: 工作项实际所属空间与请求参数中的空间 ID 不一致，请确认正确的空间。",
	},
	20015: {
		Code:        20015,
		HTTPStatus:  400,
		Message:     "Field Mix With '-' And Without '-'",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "字段参数冲突：同一字段同时出现在返回列表和排除列表中。",
		DevHint:     "20015: 请求中存在相同字段同时配置了包含和排除，请检查 field_keys 参数。",
	},
	20016: {
		Code:        20016,
		HTTPStatus:  400,
		Message:     "Node Is Not Arrived, Could Not Be Operated",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "节点未到达，无法执行流转操作。",
		DevHint:     "20016: 当前节点尚未到达，无法进行节点流转。请在工作流中推进到该节点后再试。",
	},
	20017: {
		Code:        20017,
		HTTPStatus:  400,
		Message:     "Node Is Completed, Could Not Be Completed",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "节点已经完成，无法再次完成。",
		DevHint:     "20017: 当前节点已处于完成状态，无法重复完成。请确认工作流状态。",
	},
	20018: {
		Code:        20018,
		HTTPStatus:  400,
		Message:     "Node ID Not Exist In Workflow",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "节点 ID 不存在于当前工作项的工作流配置中。",
		DevHint:     "20018: 指定的节点 ID 在当前工作项的节点流配置中不存在，请检查节点定义。",
	},
	20019: {
		Code:        20019,
		HTTPStatus:  400,
		Message:     "Invite Bot Limit 5",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "拉取群的机器人数量超过限制（最多5个）。",
		DevHint:     "20019: 拉取群的机器人数量超过 5 个上限，请减少数量后重试。",
	},
	20020: {
		Code:        20020,
		HTTPStatus:  400,
		Message:     "Bot App_ids Empty",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "拉取群机器人时未填写机器人 ID 列表。",
		DevHint:     "20020: 拉取群机器人时缺少 app_ids 参数。",
	},
	20021: {
		Code:        20021,
		HTTPStatus:  400,
		Message:     "ChatID Not Belong WorkItem",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "群 ID 不属于指定的工作项。",
		DevHint:     "20021: 传入的群 ID 与工作项无关联，请确认正确的工作项。",
	},
	20024: {
		Code:        20024,
		HTTPStatus:  400,
		Message:     "Uploaded File Size Limit 100M",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "上传文件大小超过限制（最大 100M）。",
		DevHint:     "20024: 上传附件超过 100M 限制，请压缩或分割文件后重试。",
	},
	20025: {
		Code:        20025,
		HTTPStatus:  400,
		Message:     "Field_key/Field_alias Missing",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "字段的 key 和对接标识都缺失，请至少填写其中一项。",
		DevHint:     "20025: 字段配置中同时缺少 field_key 和 field_alias，请至少填写一个。",
	},
	20026: {
		Code:        20026,
		HTTPStatus:  400,
		Message:     "FlowType Is Error, Please Convert To Status FlowType",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项是状态流类型，无法使用节点流接口。",
		DevHint:     "20026: 工作项配置为状态流，但调用了节点流接口。请改用状态流接口。",
	},
	20027: {
		Code:        20027,
		HTTPStatus:  400,
		Message:     "FlowType Is Error, Please Convert To Node FlowType",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项是节点流类型，无法使用状态流接口。",
		DevHint:     "20027: 工作项配置为节点流，但调用了状态流接口。请改用节点流接口。",
	},
	20028: {
		Code:        20028,
		HTTPStatus:  400,
		Message:     "Workitem Ids Limit 50",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "传入的工作项 ID 数量超过限制（最多50个）。",
		DevHint:     "20028: 批量操作时工作项 ID 数量不能超过 50 个，请分批处理。",
	},
	20029: {
		Code:        20029,
		HTTPStatus:  400,
		Message:     "Unsupported Field Type",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "不支持更新该类型的字段。",
		DevHint:     "20029: 该字段类型不支持更新操作，请检查字段配置。",
	},
	20032: {
		Code:        20032,
		HTTPStatus:  400,
		Message:     "DifferentSchedule Set Owner Invalid",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "差异化排期更新时，未指定用户或指定用户超过一个。",
		DevHint:     "20032: 差异化排期场景下更新排期必须指定且仅指定一个用户。",
	},
	20033: {
		Code:        20033,
		HTTPStatus:  400,
		Message:     "Update Field Invalid",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "无法更新该字段，请检查字段是否可编辑。",
		DevHint:     "20033: 该字段在当前状态下不允许更新，请检查字段配置或工作流约束。",
	},
	20037: {
		Code:        20037,
		HTTPStatus:  400,
		Message:     "Node Is Not Completed, Could Not Be Rollback",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "节点未完成，无法执行回滚操作。",
		DevHint:     "20037: 节点回滚只能在节点完成后执行，当前节点状态不允许回滚。",
	},
	20038: {
		Code:        20038,
		HTTPStatus:  400,
		Message:     "Required Field Is Not Set",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "节点完成或状态流转时，必填字段未填写。",
		DevHint:     "20038: 节点流配置中有必填字段未填写，请在流转前补充完整。",
	},
	20039: {
		Code:        20039,
		HTTPStatus:  400,
		Message:     "X-User-Key Missing (App Token)",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "使用应用级 token 请求时必须传入 X-User-Key。",
		DevHint:     "20039: 使用应用 token 时请求头中必须带上 X-User-Key。请确认请求头配置正确。",
	},
	20040: {
		Code:        20040,
		HTTPStatus:  400,
		Message:     "Request Form Is Null",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "上传附件时表单为空。",
		DevHint:     "20040: 上传附件时表单数据为空，请确认 multipart form 是否正确构造。",
	},
	20041: {
		Code:        20041,
		HTTPStatus:  400,
		Message:     "Field RoleOwner Must Be Set In FieldValuePairs",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "创建工作项时必须传入角色负责人字段。",
		DevHint:     "20041: 创建工作项时必须包含 role_owners 字段，请确认工作项类型配置。",
	},
	20042: {
		Code:        20042,
		HTTPStatus:  400,
		Message:     "X-User-Key Is Wrong, Please Check First",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "X-User-Key 未填写或值错误，请检查后重试。",
		DevHint:     "20042: 请求头中 X-User-Key 未填写或值不正确，请确认用户标识。",
	},
	20043: {
		Code:        20043,
		HTTPStatus:  400,
		Message:     "View Ids Limit 10",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "查询视图列表时最多只能传入 10 个视图 ID。",
		DevHint:     "20043: 批量查询视图时视图 ID 数量不能超过 10 个。",
	},
	20044: {
		Code:        20044,
		HTTPStatus:  400,
		Message:     "WorkItem Has Been Disabled",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项已被禁用，无法查询其元数据。",
		DevHint:     "20044: 工作项已被禁用，如需操作请先启用工作项。",
	},
	20045: {
		Code:        20045,
		HTTPStatus:  400,
		Message:     "Comment And WorkItem Not Match",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "评论不属于指定的工作项。",
		DevHint:     "20045: 评论 ID 与工作项 ID 不匹配，请确认正确的评论或工作项。",
	},
	20046: {
		Code:        20046,
		HTTPStatus:  400,
		Message:     "Task ID Not Exist In Workflow",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "子任务在工作流中不存在。",
		DevHint:     "20046: 子任务的 ID 在工作流配置中不存在，请检查子任务和工作流配置。",
	},
	20047: {
		Code:        20047,
		HTTPStatus:  400,
		Message:     "Role_Assignee and Assignee Can't Be Set Together",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "更新或创建子任务时，role_assignee 和 assignee 不能同时传入。",
		DevHint:     "20047: role_assignee 和 assignee 是互斥参数，不能同时使用，请二选一。",
	},
	20048: {
		Code:        20048,
		HTTPStatus:  400,
		Message:     "Role_Assignee's Role Is Not Match",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "role_assignee 中的角色与节点绑定的角色不匹配。",
		DevHint:     "20048: 传入的 role_assignee 角色与节点流中绑定的角色不一致，请使用正确的角色。",
	},
	20049: {
		Code:        20049,
		HTTPStatus:  400,
		Message:     "TenantGroupID Is Wrong",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "渠道用户 TenantGroupId 填写错误。",
		DevHint:     "20049: 仅渠道用户需要填写 TenantGroupId，且值不正确，请检查配置。",
	},
	20050: {
		Code:        20050,
		HTTPStatus:  400,
		Message:     "「field_key」Field Option Value Is Wrong",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "字段选项值不正确，请检查选项配置。",
		DevHint:     "20050: 传入的字段选项值在工作项类型配置中不存在或无效，请确认字段定义。",
	},
	20051: {
		Code:        20051,
		HTTPStatus:  400,
		Message:     "FieldLinkedStory Value Is Wrong",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "关联故事字段值错误。",
		DevHint:     "20051: field_linked_story 字段值不正确，请检查故事 ID 或类型是否匹配。",
	},
	20052: {
		Code:        20052,
		HTTPStatus:  400,
		Message:     "IssueOperator Value Is Wrong",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "缺陷的 operator 角色负责人填写错误。",
		DevHint:     "20052: 缺陷的 operator 角色负责人值不正确，请确认角色绑定和用户信息。",
	},
	20053: {
		Code:        20053,
		HTTPStatus:  400,
		Message:     "IssueReporter Value Is Wrong",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "缺陷的 reporter 角色负责人填写错误。",
		DevHint:     "20053: 缺陷的 reporter 角色负责人值不正确，请确认角色绑定和用户信息。",
	},
	20055: {
		Code:        20055,
		HTTPStatus:  400,
		Message:     "Search Result Bigger Than 2000, Please Check Your Search Params",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "查询结果超过 2000 个，请重新设置筛选条件缩小范围。",
		DevHint:     "20055: 搜索结果数量超过 2000 条上限，请添加更多筛选条件后重试。",
	},
	20056: {
		Code:        20056,
		HTTPStatus:  400,
		Message:     "Only WorkFlow Mode Can Be Aborted Or Restored",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "只有工作流模式可以执行终止和恢复操作。",
		DevHint:     "20056: 当前工作项不是工作流模式（而是状态流模式），不支持终止和恢复操作。",
	},
	20057: {
		Code:        20057,
		HTTPStatus:  400,
		Message:     "Search ProjectKeys And SimpleNames Limit 10",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索时 ProjectKeys 和 SimpleNames 并集不能超过 10 个。",
		DevHint:     "20057: 批量搜索时 project_keys 和 simple_names 的并集数量不能超过 10 个。",
	},
	20058: {
		Code:        20058,
		HTTPStatus:  400,
		Message:     "SearchUser.Role And SearchUser.FieldKey Can't Appear Together",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索时 Role 和 FieldKey 不能同时使用。",
		DevHint:     "20058: 搜索用户时 role 和 field_key 参数不能同时传入，请分开调用。",
	},
	20059: {
		Code:        20059,
		HTTPStatus:  400,
		Message:     "SearchUser.FieldKey Or SearchUser.Role Can't Appear Alone",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索时 UserKeys 为空时 Role 或 FieldKey 不能单独使用。",
		DevHint:     "20059: 当 user_keys 为空时，role 或 field_key 不能单独使用作为搜索条件。",
	},
	20060: {
		Code:        20060,
		HTTPStatus:  400,
		Message:     "WorkItemTypeKey Or RelationWorkItemTypeKey Is Not Match In Field Configuration",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项类型或关联工作项类型与字段配置不匹配。",
		DevHint:     "20060: 关联字段配置中的工作项类型或关联工作项类型与实际不匹配，请检查字段配置。",
	},
	20061: {
		Code:        20061,
		HTTPStatus:  400,
		Message:     "RelationKey Type Is Not Relation In Configuration",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "指定关联关系的字段类型不是关联类型。",
		DevHint:     "20061: 传入的 relation_key 字段类型不是关联类型，请确认字段配置。",
	},
	20062: {
		Code:        20062,
		HTTPStatus:  400,
		Message:     "RelationType Error",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "RelationType 值不正确，当前仅支持 0（字段key）和 1（字段alias）。",
		DevHint:     "20062: relation_type 仅支持 0=字段 key 和 1=字段 alias，请使用正确值。",
	},
	20063: {
		Code:        20063,
		HTTPStatus:  400,
		Message:     "Search Operator Error",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索操作符不正确，不同参数支持的操作符不同。",
		DevHint:     "20063: 传入的搜索操作符不被当前参数支持，请参考 API 文档确认各参数的有效操作符。",
	},
	20064: {
		Code:        20064,
		HTTPStatus:  400,
		Message:     "Search Option Size Too Large",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索时指定的选项数量超过限制（最多50个）。",
		DevHint:     "20064: 搜索选项值数量不能超过 50 个，请减少选项后重试。",
	},
	20065: {
		Code:        20065,
		HTTPStatus:  400,
		Message:     "Search Param Key Not Support StateFlow",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "当前参数不支持状态流筛选。",
		DevHint:     "20065: 该筛选参数在状态流工作项中不支持，请使用其他筛选方式。",
	},
	20066: {
		Code:        20066,
		HTTPStatus:  400,
		Message:     "Search Signal Only Support len=1 When Operator Is '=' or '!='",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "筛选系统外信号时，操作符为 = 或 != 时数组长度只能为 1。",
		DevHint:     "20066: 筛选系统外信号时，操作符为 = 或 != 时信号数组只能包含 1 个元素。",
	},
	20067: {
		Code:        20067,
		HTTPStatus:  400,
		Message:     "Search Signal Not Support Value",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "筛选系统外信号时传入的值不支持该筛选方式。",
		DevHint:     "20067: 系统外信号筛选不支持该值类型或操作方式，请检查筛选表达式。",
	},
	20068: {
		Code:        20068,
		HTTPStatus:  400,
		Message:     "Search Param Is Not Support",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "指定的参数不支持筛选。",
		DevHint:     "20068: 该参数在工作项类型的字段配置中不支持筛选，请使用支持的参数。",
	},
	20069: {
		Code:        20069,
		HTTPStatus:  400,
		Message:     "Search Param Value Error",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索参数值异常，请检查格式。",
		DevHint:     "20069: 搜索参数值格式或范围异常，请检查筛选值是否符合字段定义。",
	},
	20070: {
		Code:        20070,
		HTTPStatus:  400,
		Message:     "Field Is Invalid",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "上传附件时指定的字段已失效。",
		DevHint:     "20070: 附件上传指定的字段在当前工作项类型中已失效或不存在。",
	},
	20071: {
		Code:        20071,
		HTTPStatus:  400,
		Message:     "Search People Not Support Issue",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "缺陷类型工作项不支持通过 people 参数筛选。",
		DevHint:     "20071: people 筛选条件在缺陷工作项类型中不支持，请使用其他字段筛选。",
	},
	20072: {
		Code:        20072,
		HTTPStatus:  400,
		Message:     "Conjunction Value Only Support 'AND', 'OR'",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "搜索的 Conjunction 仅支持 AND 或 OR。",
		DevHint:     "20072: conjunction 参数值必须为 AND 或 OR，请使用正确的大写形式。",
	},
	20080: {
		Code:        20080,
		HTTPStatus:  400,
		Message:     "Query Length Must Be Larger Than 0, Smaller Than 200",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "综搜 query 长度必须大于 0 且小于 200。",
		DevHint:     "20080: 综搜接口 query 参数长度必须在 1-199 字符之间。",
	},
	20081: {
		Code:        20081,
		HTTPStatus:  400,
		Message:     "Query Type Is Not Supported",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "综搜不支持该查询类型，当前仅支持查询工作项和视图。",
		DevHint:     "20081: query_type 目前仅支持工作项(workitem)和视图(view)两种类型。",
	},
	20082: {
		Code:        20082,
		HTTPStatus:  400,
		Message:     "Action Is Not Supported",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "子任务状态更新接口仅支持回滚和确认操作。",
		DevHint:     "20082: 子任务状态更新接口的 action 参数仅支持 rollback 和 confirm。",
	},
	20083: {
		Code:        20083,
		HTTPStatus:  400,
		Message:     "Duplication Field Exist, FieldKey",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "创建工作项时传入了重复字段。",
		DevHint:     "20083: 创建工作项时 field_value_pairs 中存在重复的 field_key，请去重后重试。",
	},
	20090: {
		Code:        20090,
		HTTPStatus:  400,
		Message:     "Your Request Has Been Intercepted",
		Category:    CategoryValidation,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "请求被插件拦截，请检查插件配置或联系插件开发者。",
		DevHint:     "20090: 请求被业务插件拦截，不允许执行。请检查是否有自定义插件阻止了该操作。",
	},

	// ─── 资源未找到 (HTTP 404, 1xxxx / 3xxxx) ─────────────────────────────────

	13001: {
		Code:        13001,
		HTTPStatus:  404,
		Message:     "View Not Exist",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "视图不存在，可能已被删除。",
		DevHint:     "13001: 视图 ID 不存在或已被删除，请确认正确的视图 ID。",
	},
	30005: {
		Code:        30005,
		HTTPStatus:  404,
		Message:     "WorkItem Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项未找到，可能已删除或 ID 不正确。",
		DevHint:     "30005: 工作项不存在，可能原因：1) 工作项已删除 2) 查询的 ID 不正确 3) 工作项类型与 ID 不匹配。请确认工作项 ID。",
	},
	30006: {
		Code:        30006,
		HTTPStatus:  404,
		Message:     "User Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "未查到指定用户，可能是使用了虚拟 token 导致无法查到非协作者信息。",
		DevHint:     "30006: 用户不存在或无法被查询到。如果是虚拟 token，仅能查到插件协作者信息。请确认插件是否已共享到插件市场。",
	},
	30007: {
		Code:        30007,
		HTTPStatus:  404,
		Message:     "Workflow Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项中未找到节点流配置。",
		DevHint:     "30007: 工作项的节点流配置不存在，请确认该工作项是否配置了节点流。",
	},
	30008: {
		Code:        30008,
		HTTPStatus:  404,
		Message:     "Business Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "空间下的业务线未找到。",
		DevHint:     "30008: 指定的业务线在目标空间中不存在，请确认业务线 ID。",
	},
	30009: {
		Code:        30009,
		HTTPStatus:  404,
		Message:     "Field Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "字段未在字段配置中找到，无法更新或创建。",
		DevHint:     "30009: 字段在工作项类型的字段配置中不存在，请先在字段配置中添加该字段。",
	},
	30010: {
		Code:        30010,
		HTTPStatus:  404,
		Message:     "Stateflow Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "工作项中未找到状态流配置。",
		DevHint:     "30010: 工作项的节点流配置不存在，请确认该工作项是否配置了状态流。",
	},
	30011: {
		Code:        30011,
		HTTPStatus:  404,
		Message:     "Node Not Found In Workflow",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "节点在工作项的节点流配置中未找到。",
		DevHint:     "30011: 指定的节点 ID 在当前工作项的节点流配置中不存在，请检查节点定义。",
	},
	30012: {
		Code:        30012,
		HTTPStatus:  404,
		Message:     "State Not Found In Stateflow",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "状态在当前工作项的状态流配置中未找到。",
		DevHint:     "30012: 指定的节点/状态 ID 在工作项的状态流配置中不存在，请检查状态定义。",
	},
	30015: {
		Code:        30015,
		HTTPStatus:  404,
		Message:     "Record Not Found",
		Category:    CategoryNotFound,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "记录不存在，评论 ID 不存在。",
		DevHint:     "30015: 更新评论失败，评论 ID 不存在或已删除，请确认正确的评论 ID。",
	},

	// ─── 服务端错误 (HTTP 500) ────────────────────────────────────────────────

	50006: {
		Code:         50006,
		HTTPStatus:   500,
		Message:      "RPC Call Error / openapi system err",
		Category:     CategoryServer,
		Retryable:    true,
		RefreshToken: false,
		MaxRetry:     2,
		UserHint:     "服务端异常，请稍后重试。",
		DevHint:      "50006: 服务端内部错误。请实现指数退避重试。如果问题持续，请联系飞书技术支持。",
	},

	// ─── 其他业务错误 (HTTP 400) ───────────────────────────────────────────────

	9999: {
		Code:        9999,
		HTTPStatus:  400,
		Message:     "Invalid Param",
		Category:    CategoryClient,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "数据结构不匹配，请检查入参格式。",
		DevHint:     "9999: 请求数据结构与 API 定义不匹配，请检查请求体格式、字段类型和必填项。",
	},
	1000051942: {
		Code:        1000051942,
		HTTPStatus:  400,
		Message:     "Commercial Usage Exceeded",
		Category:    CategoryClient,
		Retryable:   false,
		MaxRetry:    0,
		UserHint:    "商业化用量超限，请检查套餐余量或升级方案。",
		DevHint:     "1000051942: 商业化用量超过套餐限制。请前往飞书项目管理后台查看用量详情并处理。",
	},
}

// LookupPolicy returns the policy for a given error code.
// If the error code is unknown, returns a default policy with CategoryUnknown.
func LookupPolicy(code int) Policy {
	if p, ok := Policies[code]; ok {
		return p
	}
	return Policy{
		Code:         code,
		HTTPStatus:   0,
		Category:     CategoryUnknown,
		Retryable:    false,
		RefreshToken: false,
		MaxRetry:     0,
		UserHint:     "请求失败，请检查错误信息或开启 debug 查看详情。",
		DevHint:      "unknown openapi error code",
	}
}
